### ISSUE TITLE
Add separate section link that opens the section for editing with ProveIt maximized

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#121]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on November 18, 2011 19:31:27_

This was initially suggested by Nathan:

"I also propose a variation of this tool that adds a call link to article-space, at the end of each paragraph or at least the last graf in each section. (Or, alternatively, as a tool-bar button at the top of an article, with a section-selector step built into the tool). Any thoughts on this? Seems like it would be really useful, and could potentially be incorporated into MediaWiki as an extension to make it enabled by default for all users (including IP readers)."

Essentially, add an additional section link with the additional behavior of maximizing ProveIt by default.  This would be useful already, but more so in combination with issue #93.  Users could save screen real estate while still easily opening ProveIt while reading.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=123_

**Comment by Sophivorus** [comment]
WONTFIX
Now that the code is hosted at Commons, adding these links in the article space would require a request to Commons for every page load of users with the gadget enabled.
The code for adding the link **could** be added to the initialization code, thus avoiding the call to Commons, but the functionality seems barely useful to me, because all it does is save one click to maximize the gadget. Stronger arguments should be given.
