### ISSUE TITLE
Make translation and localization for other languages and Wikipedias easier

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#136]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on March 31, 2012 00:12:42_

Right now, some of the Proveit interface (including field descriptions) is localized.  Other parts are not yet, but this can be fixed relatively easily.

However, localizations are placed into the main ProveIt code, which may couple localization to code more than necessary.  The system also works better for translations running on English Wikipedias than for other Wikipedias.

Make it easier to localize both for other Wikipedias (e.g. Farsi), and for users who wish to use a different user interface than the Wikipedia content language.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=139_

**Comment by lfschenone** [comment]
The latest version seems to solve this issue as described by the title. However, there are still some i18n issues left, like using the wgUserLanguage configuration option and the mw.messages functionality. But I think we should create new and specific issues for that, rather than having a very general one like this one. Should we close this issue then?

**Comment by mattflaschen** [comment]
Yeah, I'm fine with closing it if the specific ones are created first.

**Comment by sophivorus** [comment]
The very latest version uses the wgUserLanguage option and the mw.messages functionality, so neither this nor the specific issues seem no longer relevant.
