### ISSUE TITLE
Website broken

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#205]
"Add a Reference" is broken on the demo, probably related to the recent changes with jQuery UI Tabs.

**Comment by fireattack** [comment]
Here the demo site (http://proveit.wmflabs.org/demo?) doesn't work at all. Can't load pages from Wikipedia.

**Comment by lfschenone** [comment]
I'll try to fix this, but before I do I must ask: is all of this website really necessary? In my opinion, the smaller we keep the codebase the better, because that way it's easier to maintain and it's easier for other developers to join. In principle, we could get rid completely of this website and create a page for ProveIt under Commons, Wikipedia or Wikitech. I suggest Commons, see https://commons.wikimedia.org/wiki/Help:Gadget-HotCat. It would then be easy to add a demo by linking to a few articles with the withJS and withCSS parameters, like I did here: https://commons.wikimedia.org/wiki/Commons:WikiProject_WikiWidgets/demo
Also consider the advantages of hosting the ProveIt code under Commons and then just linking to it from the various Wikipedias, see for example https://es.wikipedia.org/wiki/MediaWiki:Gadget-HotCat.js
But I don't want to insist too much, I know my place. If you prefer to keep the website, I'm ok with fixing it. Cheers.

**Comment by fireattack** [comment]
I fully agree with you, if we really need a standalone demo site.

**Comment by Sophivorus** [comment]
@mattflaschen Hi Matt, do you agree? If so, please replace the website with a redirect to https://commons.wikimedia.org/wiki/Help:Gadget-ProveIt, I can't do it myself because I don't have access to the web root.

**Comment by Sophivorus** [comment]
Migrated to https://phabricator.wikimedia.org/T148228
