### ISSUE TITLE
Serve code from Commons

### ISSUE THREAD

**Issue by Sophivorus** [proveit-js/proveit#219]
I think we should request the pages MediaWiki:Gadget-ProveIt.js and MediaWiki:Gadget-ProveIt.css be created at Commons with the latest code. Wikipedias can then load the code like they do with HotCat and other gadgets, see https://en.wikipedia.org/wiki/MediaWiki:Gadget-HotCat.js

The code would need some update so that each Wikipedia loads its own i18n file, I can take care of this.

Centralising code at Commons would keep the gadget updated in all Wikipedias at the same time, simplifying maintenance and collaboration. I think the advantages are obvious. What do you think?

**Comment by sophivorus** [comment]
I have requested the repository at Gerrit. Every repo created at Commons gets a mirror at Github, so the workflow wouldn't change, we'd just need to migrate the issues somehow.

I think that if we migrate to Gerrit, ProveIt would be the first gadget hosted there, and would set the example for other gadgets to follow. The current gadget landscape is a mighty mess, with different versions of different gadgets distributed through hundreds of wikis. The community could benefit greatly from a centralised repository of gadgets, and the most natural solution to that would be to host them at Gerrit + Github mirrors. But what do you think?

**Comment by sophivorus** [comment]
@mattflaschen The repo has already been created:
`git clone https://gerrit.wikimedia.org/r/wikipedia/gadgets/ProveIt`
Should we migrate the issues and continue work from the GitHub mirror at https://github.com/wikimedia/wikipedia-gadgets-ProveIt ?

**Comment by mattflaschen** [comment]
I have no objections to this idea.  It will indeed make it a lot easier as more wikis start using it.

The only downsides are:

1. Slightly slower to load, since it has to request more files.  Not that big a deal.
2. Need to find someone to always update the Commons file(s) when the main code changes.

Also, need to make sure that Commons is still a mirror of the main code (whether the main code is on Gerrit or GitHub).  If people try to make changes directly to Commons, it should be reverted and submitted as a pull request here (same issue applies to Wikipedia, just something to be aware of).

Also, regardless of where the code is, people can use the [deployment script](https://github.com/proveit-js/proveit/blob/master/deploy.php) if they want (I recommend it but not everyone wants to bother setting up PHP on their machine).

**Comment by Sophivorus** [comment]
The code is now served from Commons, both for the Spanish and English Wikipedias:
* https://commons.wikimedia.org/wiki/MediaWiki:Gadget-ProveIt.js
* https://commons.wikimedia.org/wiki/MediaWiki:Gadget-ProveIt.css
* https://en.wikipedia.org/wiki/MediaWiki:Gadget-ProveIt.js
* https://es.wikipedia.org/wiki/MediaWiki:Gadget-ProveIt.js

I've been granted the global-interface-editor right for one year, so I'll be able to keep the code updated at Commons for at least one year.
