### ISSUE TITLE
How can make ProveIt work on wikia sites?

### ISSUE THREAD

**Issue by PhongTong** [proveit-js/proveit#225]
Thank you :)

**Comment by Sophivorus** [comment]
Hi @PhongTong! The gadget now relies on the [Extension:TemplateData](https://www.mediawiki.org/wiki/Extension:TemplateData), so you need to make sure that Wikia has enabled the extension for your wiki. If they did, then proceed to define the gadget at MediaWiki:Gadgets-definition like so:
````
* ProveIt [ResourceLoader] ProveIt.js | ProveIt.css
````
and copy the source code of the gadget (the proveit.js and proveit.css files) to MediaWiki:Gadget-ProveIt.js and MediaWiki:Gadget-ProveIt.css

Next, you need to connect the gadget with the citation templates you want it to handle. To do so, you need to:

1. Fill the TemplateData for your templates, see the documentation of the [Template:Cite book](https://en.wikipedia.org/wiki/Template:Cite_book) in the English Wikipedia for an example.

2. Create a category and add all the templates to it, see for example the [Category:ProveIt](https://en.wikipedia.org/wiki/Category:ProveIt) in the English Wikipedia.

3. Modify the source code of MediaWiki:Gadget-ProveIt.js so that ProveIt knows in which category to look for its templates. Assuming that the language of your wiki is English, look for the following code:
````
settings: {
	'en': {
		'category': 'Category:ProveIt',
		'tag': 'ProveIt edit',
	},
````
And replace it for:
````
settings: {
	'en': {
		'category': 'Category:Name of the category you created',
		'tag': null, // Only set this if you created a #proveit rev tag at Special:Tags
	},
````
If your wiki is not in English, then replace "en" for the language code of your wiki.

Good luck, and let me know how it goes! I'm closing this task now, but please reopen it if you need to.
