### ISSUE TITLE
Misc examples of refs that don't load

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#63]
_From [kurt.luther](https://code.google.com/u/kurt.luther/) on October 05, 2010 11:57:15_

http://en.wikipedia.org/wiki/Social_computing Two examples on this page of refs that won't load in ProveIt.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=63_

**Comment by NotACat** [comment]
This is still an issue. Any chance of some action at any point?

**Comment by jbnx42** [comment]
IMHO, this is a big issue since ProveIt seems to be at odds with explicit instructions given by a prominent cite template . I was editing an article and tried to include the author parameter for no authors as suggested in the Template:Cite news help screen. This is recommended as `author=<!--Staff writer(s); no by-line.-->`. Due to this issue, the ref disappeared from the available reference in ProveIt. I would urge the escalation of this issue since it may discourage wikipedians who would simply be puzzled by the behavior and therefore turned off from the contribution process.

**Comment by Sophivorus** [comment]
The latest regex seems to have no issues with the HTML comments. Hooray!
