### ISSUE TITLE
ProveIt should create reference list (<references/>) when possible

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#69]
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on October 19, 2010 22:57:30_

When the user is editing the whole page (not a section), and they create the first reference, ProveIt should add (or offer to add) a <references /> tag, if it does not exist.

It should place this in a References section, which may already exist.  If it doesn't, the section should be added to the page.  It should be placed after all others except "External links".

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=69_

**Comment by lfschenone** [comment]
I don't think this is a good idea. Many if not all Wikipedias use one or more templates to insert the <references/> tag, to control for example the number of columns in the references section. Also, the location of the references section may vary among wikipedias (in some it may be the last section, in others the section before the last, etc). All these variations make the feature very difficult to implement, and it isn't even that useful, because if the <references/> tag is not found, the Cite extension will show the references at the very bottom of the article, which isn't at all bad until someone corrects it according to the relevant conventions.

For these reasons, I'm closing this issue, but please reopen it if you think it deserves further consideration.
