### ISSUE TITLE
Toggle suggestion

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#92]
_From [jorlowitz1](https://code.google.com/u/115595203472278741123/) on December 27, 2010 00:16:59_

This is not a bug, but a suggestion.  The program looks and works great.

Issue: Sometimes I don't want the proveit toolbar to pop-up

Solution:  An option to minimize or hide it

Implementation:  Double-click, toggle button, drag to minimize, keyboard shortcut (any of the above)

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=93_

**Comment by lfschenone** [comment]
Starting maximised/minimised/hidden used to be a configuration option in the pre-i18n version. The current version removes this option to simplify the code and make a configuration tab unnecessary. I support this approach, but in order to fulfil this request, we could use a cookie to track the current preferred state, meaning that if a user hides the gadget, a cookie is set so that the next time the page loads, it stays hidden.

**Comment by Sophivorus** [comment]
There were several unrelated complaints regarding the bottom bar minimization, so I changed the behaviors so that ProveIt now minimizes to a corner rather than bar.

![screen shot 2016-08-11 at 12 12 42 am](https://cloud.githubusercontent.com/assets/3542266/17577794/5933d0d0-5f58-11e6-8234-7e5a797f68a8.png)
